version: '3.7'
services:
  db:
    container_name: db-container
    image: postgres:13
    restart: always
    ports:
      - '$DB_PORT:$DB_PORT'
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # pgadmin:
  #   container_name: admin-db-container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=$PG_ADMIN_LOGIN
  #     - PGADMIN_DEFAULT_PASSWORD=$PG_ADMIN_PASSWORD
  #   volumes:
  #      - pgadmin_data:/var/lib/pgadmin
  #   ports:
  #     - '5050:80'
  #   depends_on:
  #     - db

  server:
    container_name: server-container
    image: node:19.1-alpine
    user: "${UID}:${GID}"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '$SERVER_PORT:$SERVER_PORT'
    environment:
      - SERVER_PORT=$SERVER_PORT
      - DB_SERVICE_NAME=$DB_SERVICE_NAME
      - DB_PORT=$DB_PORT
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    command: [ "npm", "run", "start:dev" ]
    depends_on:
      - db

volumes:
  postgres_data:
  # pgadmin_data: